// src/localization.ts
export type Locale = 'ru' | 'en';

export const defaultLocale: Locale = 'en';

export const translations: Record<Locale, Record<string, string>> = {
  ru: {
    language: 'Язык',
    save: 'Сохранить',
    cancel: 'Сбросить',
    chatTitle: 'Groq Чат',
    authToken: 'Токен авторизации',
    apiKey: 'API ключ',
    apiKeyPlaceholder: 'Введите API ключ',
    checkApiKey: 'Проверить',
    validApiKey: '✅ Ключ действителен',
    invalidApiKey: '❌ Неверный ключ',
    model: 'Модель',
    active: 'Активна',
    requestsLeft: 'Осталось запросов',
    tokensLeft: 'Осталось токенов',
    reset: 'Сброс',
    status: 'Статус',
    temperature: 'Температура',
    maxTokens: 'Макс. токенов',
    maxTokensPlaceholder: 'Введите число',
    history: 'Хранение истории',
    historyLengthPlaceholder: '20',
    historyFile: 'Файл истории',
    historyFilePlaceholder: 'groq-chat-history.md',
    displayMode: 'Режим отображения',
    tab: 'Во вкладке',
    sidepanel: 'В боковой панели',
    // Tooltips & Dialogs
    supportDev: 'Поддержать разработку',
    supportDevShort: 'Поддержать',
    supportDevHeader: 'Поддержать разработчика',
    modelInfo: 'Информация о модели',
    description: 'Описание',
    developer: 'Разработчик',
    releaseDate: 'Дата выпуска',
    actualDate: 'Дата актуальности',
    releaseStatus: 'Статус релиза',
    close: 'Закрыть',
    modelUnavailable: 'Эта модель временно недоступна',
    showInSidepanel: 'Показать в боковой панели',
    showInTab: 'Показать во вкладке',
    scrollToTop: 'К началу диалога',
    scrollToBottom: 'К концу диалога',
    clearHistory: 'Очистить историю',
    showFormatting: 'Показать форматирование',
    showRaw: 'Показать исходный код',
    copyMessage: 'Копировать сообщение',
    copyError: 'Ошибка копирования',
    chooseModel: 'Выберите модель Groq',
    copyCode: 'Копировать код',
    refreshModels: 'Обновить модели',
    modelsUpdated: 'Список моделей обновлён',
    modelsUpdateError: 'Ошибка при обновлении списка моделей',
    noModelsFound: 'Нет доступных моделей',
    imageNotice:
      '⚠️ Чат не поддерживает отображение изображений. Если модель возвращает абсолютную ссылку на изображение, будет показана только ссылка.',
    // Input (MessageInput)
    inputPlaceholder: 'Введите сообщение...',
    inputAriaLabel: 'Поле ввода сообщения',
    sendMessage: 'Отправить сообщение',
    sendTitle: 'Отправить (Ctrl+Enter)',
    inputHint:
      '<kbd>Ctrl</kbd>+<kbd>Enter</kbd> — отправить, <kbd>Shift</kbd>+<kbd>Enter</kbd> — новая строка',
    inputCounterTitle:
      'Текущее кол-во символов / Макс. кол-во токенов для модели (приблизительное сравнение)',
    symbolsTokens: 'символы/токены',
  },
  en: {
    language: 'Language',
    save: 'Save',
    cancel: 'Reset',
    chatTitle: 'Groq Chat',
    authToken: 'Auth Token',
    apiKey: 'API Key',
    apiKeyPlaceholder: 'Enter API key',
    checkApiKey: 'Check',
    validApiKey: '✅ Key is valid',
    invalidApiKey: '❌ Invalid key',
    model: 'Model',
    active: 'Active',
    requestsLeft: 'Requests left',
    tokensLeft: 'Tokens left',
    reset: 'Reset',
    status: 'Status',
    temperature: 'Temperature',
    maxTokens: 'Max tokens',
    maxTokensPlaceholder: 'Enter a number',
    history: 'History storage',
    historyLengthPlaceholder: '20',
    historyFile: 'History file',
    historyFilePlaceholder: 'groq-chat-history.md',
    displayMode: 'Display mode',
    tab: 'In tab',
    sidepanel: 'In side panel',
    // Tooltips & Dialogs
    supportDev: 'Support development',
    supportDevShort: 'Support',
    supportDevHeader: 'Support developer',
    modelInfo: 'Model info',
    description: 'Description',
    developer: 'Developer',
    releaseDate: 'Release date',
    actualDate: 'Actual date',
    releaseStatus: 'Release status',
    close: 'Close',
    modelUnavailable: 'This model is temporarily unavailable',
    showInSidepanel: 'Show in side panel',
    showInTab: 'Show in tab',
    scrollToTop: 'Scroll to top',
    scrollToBottom: 'Scroll to bottom',
    clearHistory: 'Clear history',
    showFormatting: 'Show formatting',
    showRaw: 'Show raw',
    copyMessage: 'Copy message',
    copyError: 'Copy error',
    chooseModel: 'Choose Groq model',
    copyCode: 'Copy code',
    refreshModels: 'Refresh models',
    modelsUpdated: 'Model list updated',
    modelsUpdateError: 'Error updating model list',
    noModelsFound: 'No available models',
    imageNotice:
      '⚠️ Chat does not support image rendering. If the model returns an absolute image link, only the link will be shown.',
    // Input (MessageInput)
    inputPlaceholder: 'Type a message...',
    inputAriaLabel: 'Message input field',
    sendMessage: 'Send message',
    sendTitle: 'Send (Ctrl+Enter)',
    inputHint:
      '<kbd>Ctrl</kbd>+<kbd>Enter</kbd> — send, <kbd>Shift</kbd>+<kbd>Enter</kbd> — new line',
    inputCounterTitle: 'Current character count / Max model tokens (approximate)',
    symbolsTokens: 'chars/tokens',
  },
};

export function t(key: string, locale: Locale = defaultLocale): string {
  return translations[locale][key] || key;
}
